version: '3'
services:
  app:
    image: dominio/dotnet-helloword:latest
    restart: unless-stopped
    container_name: dotnet-helloword
    volumes:
      - ./src/HelloWord.Dotnet.Api/appsettings.Development.json:/app/appsettings.json
    ports:
      - "5000:80"
#Volumes
volumes:
  dbdata:
    driver: local
